version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auto_ria_db
    restart: always
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: auto_ria_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./dumps:/app/dumps 
    environment:
      - host=db

volumes:
  postgres_data:
