version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auto_ria_db
    restart: always
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user} 
      POSTGRES_PASSWORD: ${password}
    ports:
      - "${sport}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # AUTOMATIC TABLE CREATION:
      - ./database/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  app:
    image: bontonent/auto_ria:latest
    build: .
    container_name: auto_ria_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app 
    environment:
      - host=db
      - database=${database}
      - port=${port}
      - user=${user}
      - password=${password}

volumes:
  postgres_data: